package vistas;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class CuadradosMedios extends javax.swing.JDialog {
    DefaultTableModel modelo;
    //Constructor
    public CuadradosMedios(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        //Alineamos a la vistaPrincipal
        setLocationRelativeTo(parent);
        this.setLocationRelativeTo(null);
//        modelo= new DefaultTableModel();
//        modelo.addColumn("Iteraccion");
//        modelo.addColumn("Semilla Xi0");
//        modelo.addColumn("Semilla Xi1");
//        modelo.addColumn("Semilla^2");
//        modelo.addColumn("Semilla Xi+1");
//        modelo.addColumn("Pseudonumero");
//        this.jTable1.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo1 = new javax.swing.ButtonGroup();
        panel1 = new javax.swing.JPanel();
        label1 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        label4 = new javax.swing.JLabel();
        textField1 = new javax.swing.JTextField();
        textField3 = new javax.swing.JTextField();
        boton1 = new javax.swing.JButton();
        boton2 = new javax.swing.JButton();
        radioDerecha = new javax.swing.JRadioButton();
        radioIzquierda = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panel1.setBackground(new java.awt.Color(35, 41, 70));

        label1.setBackground(new java.awt.Color(255, 255, 255));
        label1.setFont(new java.awt.Font("Segoe UI", 1, 40)); // NOI18N
        label1.setForeground(new java.awt.Color(255, 255, 255));
        label1.setText("Algoritmo de Productos Medios");

        label2.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        label2.setForeground(new java.awt.Color(184, 193, 236));
        label2.setText("Ingrese la semilla x0");

        label4.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        label4.setForeground(new java.awt.Color(184, 193, 236));
        label4.setText("Ingrese las repeticiones");

        textField1.setBackground(new java.awt.Color(255, 255, 255));

        textField3.setBackground(new java.awt.Color(255, 255, 255));

        boton1.setBackground(new java.awt.Color(238, 187, 195));
        boton1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        boton1.setForeground(new java.awt.Color(35, 41, 70));
        boton1.setText("Generar");
        boton1.setMaximumSize(new java.awt.Dimension(100, 50));
        boton1.setMinimumSize(new java.awt.Dimension(100, 50));
        boton1.setPreferredSize(new java.awt.Dimension(100, 50));
        boton1.setRequestFocusEnabled(false);
        boton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton1MouseClicked(evt);
            }
        });

        boton2.setBackground(new java.awt.Color(238, 187, 195));
        boton2.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        boton2.setForeground(new java.awt.Color(35, 41, 70));
        boton2.setText("Limpiar");
        boton2.setMaximumSize(new java.awt.Dimension(100, 50));
        boton2.setMinimumSize(new java.awt.Dimension(100, 50));
        boton2.setPreferredSize(new java.awt.Dimension(100, 50));
        boton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boton2MouseClicked(evt);
            }
        });

        grupo1.add(radioDerecha);
        radioDerecha.setText("Cero a la derecha");

        grupo1.add(radioIzquierda);
        radioIzquierda.setText("Cero a la izquierda");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Iteración ", "Semilla Xi", "Semilla^2", "Semilla Xi+1", "Pseudonumero"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel1Layout.createSequentialGroup()
                .addGap(0, 172, Short.MAX_VALUE)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 689, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(153, 153, 153))
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(radioIzquierda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(radioDerecha))
                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(75, 75, 75)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textField3, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(boton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(boton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(label1)
                .addGap(65, 65, 65)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label2)
                    .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label4)
                    .addComponent(textField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioIzquierda)
                    .addComponent(radioDerecha)
                    .addComponent(boton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(114, 114, 114)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        getContentPane().add(panel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Metodo boton1
    private void boton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton1MouseClicked
        //Guardamos el resultado de los campos
        String semilla = textField1.getText();
        String repeticionesString = textField3.getText();
        
        //Verificamos si los RadioButton han sido selecionados
        boolean selecion1 = radioIzquierda.isSelected();
        boolean selecion2 = radioDerecha.isSelected(); 
        
        //Verificamos si todos los campos fueron selecionados
        if(semilla.isEmpty() || repeticionesString.isEmpty() || ( !selecion1 && !selecion2)){
            JOptionPane.showMessageDialog(null,"Complete todos los campos");
        }else{
            // Guardamos el tamanio de la semilla
            int sizeSemilla = semilla.length();
            if(sizeSemilla < 4){
                JOptionPane.showMessageDialog(null,"La semilla debe ser mayor de 3 digitos");
            }else{
                JOptionPane.showMessageDialog(null,"perfecto");
                //Verificamos que radioButton eligio
                long digitosSemilla = semilla.length();
                int repeticionesInt = Integer.parseInt(repeticionesString);
                String [] fila= new String [5];
                
                //Variables
                long resultado1 = 0;
                String nuevaSemillaString;
                int sizeSemillaNueva = 0;
                
                        
                if(selecion1){
                    for(int i = 0; i < repeticionesInt; ++i){
                       resultado1 = (long)Math.pow(digitosSemilla, 2);
                       nuevaSemillaString = Long.toString(resultado1);
                       sizeSemillaNueva = nuevaSemillaString.length();
                    }
                }else{
                    
                }
            }
                
        }
        
//       
    }//GEN-LAST:event_boton1MouseClicked
    
    //Metodo boton2
    private void boton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boton2MouseClicked
    try{
        textField1.setText("");
        textField3.setText("");
        }catch(Exception e){
        JOptionPane.showMessageDialog(null,"Hubo dificultades en el programa","ERROR",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_boton2MouseClicked
    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(CuadradosMedios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(CuadradosMedios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(CuadradosMedios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(CuadradosMedios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                CuadradosMedios dialog = new CuadradosMedios(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton1;
    private javax.swing.JButton boton2;
    private javax.swing.ButtonGroup grupo1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label4;
    private javax.swing.JPanel panel1;
    private javax.swing.JRadioButton radioDerecha;
    private javax.swing.JRadioButton radioIzquierda;
    private javax.swing.JTextField textField1;
    private javax.swing.JTextField textField3;
    // End of variables declaration//GEN-END:variables
}
