package vistas;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Valencia
 */
public class NCMultiplicadorConstante extends javax.swing.JDialog {

        DefaultTableModel modelo;
    /**
     * Creates new form MultiplicadorConstante
     */
        //Constructor
    public NCMultiplicadorConstante(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        modelo = new DefaultTableModel();
        modelo.addColumn("Iteraccion");
        modelo.addColumn("Constante");
        modelo.addColumn("Semilla Xi");
        modelo.addColumn("Semilla^2");
        modelo.addColumn("Semilla Xi+1");
        modelo.addColumn("Pseudonumero");
        this.T1.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Constante = new javax.swing.JTextField();
        Repeticiones = new javax.swing.JTextField();
        B2 = new javax.swing.JButton();
        BGenerar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        Semillax0 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        T1 = new javax.swing.JTable();
        CD = new javax.swing.JRadioButton();
        CI = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jPanel1.setBackground(new java.awt.Color(40, 42, 54));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        jLabel1.setFont(new java.awt.Font("Baskerville Old Face", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Multiplicador Constante");

        jLabel2.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Repeticiones:");

        jLabel3.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Constante:");

        Constante.setBackground(new java.awt.Color(255, 255, 255));
        Constante.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        Constante.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Constante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConstanteActionPerformed(evt);
            }
        });

        Repeticiones.setBackground(new java.awt.Color(255, 255, 255));
        Repeticiones.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        Repeticiones.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Repeticiones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RepeticionesActionPerformed(evt);
            }
        });

        B2.setBackground(new java.awt.Color(0, 0, 0));
        B2.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        B2.setForeground(new java.awt.Color(255, 255, 255));
        B2.setText("Limpiar");
        B2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        B2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B2MouseClicked(evt);
            }
        });

        BGenerar.setBackground(new java.awt.Color(0, 0, 0));
        BGenerar.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        BGenerar.setForeground(new java.awt.Color(255, 255, 255));
        BGenerar.setText("Generar");
        BGenerar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        BGenerar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BGenerarMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Semilla x0:");

        Semillax0.setBackground(new java.awt.Color(255, 255, 255));
        Semillax0.setFont(new java.awt.Font("Cambria Math", 0, 18)); // NOI18N
        Semillax0.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Semillax0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Semillax0ActionPerformed(evt);
            }
        });

        T1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Iteraccion", "Constante", "Semilla Xi", "Semilla ^2", "Semilla Xi+1", "Pseudonumero"
            }
        ));
        jScrollPane1.setViewportView(T1);

        CD.setBackground(new java.awt.Color(40, 42, 54));
        CD.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        CD.setForeground(new java.awt.Color(255, 255, 255));
        CD.setText("Cero a la derecha");

        CI.setBackground(new java.awt.Color(40, 42, 54));
        CI.setFont(new java.awt.Font("Cambria Math", 0, 14)); // NOI18N
        CI.setForeground(new java.awt.Color(255, 255, 255));
        CI.setText("Cero a la izquierda");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addComponent(BGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(B2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(53, 53, 53)
                            .addComponent(CD)
                            .addGap(18, 18, 18)
                            .addComponent(CI))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(Constante, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(Semillax0, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(Repeticiones, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(34, 34, 34)
                            .addComponent(jLabel1))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Constante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(Semillax0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(Repeticiones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CD)
                            .addComponent(CI))))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ConstanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConstanteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConstanteActionPerformed

    private void RepeticionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RepeticionesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RepeticionesActionPerformed

    private void BGenerarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BGenerarMouseClicked
        //Declaracion de las variables
        String se  = Semillax0.getText();
        String re  = Repeticiones.getText();
        String con = Constante.getText();
        String snum,snum2,snum3, snum4;
        int ciclo = Integer.parseInt(re);
        int dato = se.length();
        int dato2,i,pch;
        long num1,num2,num3;
        double num4;
    
            if(dato < 4){
                JOptionPane.showMessageDialog(null,"En la semilla debe iniciar un numero mayor de 3 cifras");
                Semillax0.setText("");
            }else
            if(se.isEmpty() || re.isEmpty()){
                JOptionPane.showMessageDialog(null,"No deje nungun campo vacio");
                
            } else
            //Comienza la evaluacion si es cero a la izquierda
          if(CI.isSelected()){
              num1 = Long.parseLong(se);
            num2 = Long.parseLong(con);
            snum2 = con;
          String [] fila = new String [6];
            for(i=0;i<Integer.parseInt(re);i++)
            {
                num3 = (long)(num1 * num2);
                snum3 = Long.toString(num3);
                dato2 = snum3.length();
                pch = (dato2-dato)/2;
                snum4=snum3.substring(pch, pch+dato);
                num4= Double.parseDouble(snum4)/(Math.pow(10, dato));
               snum= Long.toString(num1);
                    fila[0]=Integer.toString(i);
                    fila[1]=snum2;
                    fila[2]=snum;
                    fila[3]=snum3;
                    fila[4]=snum4;
                    fila[5]=Double.toString(num4);
                    modelo.addRow(fila);
                    num1=Long.parseLong(snum4);
            }
            
             //Comienza la evaluacion si es cero a la derecha
    }else if(CD.isSelected()){
    num1= Long.parseLong(se);
                    num2= Long.parseLong(con);
                    snum2=con;
                String [] fila= new String [6];
                if(dato%2==0){   
                    for(i=0;i<Integer.parseInt(re);i++){
                        num3= (long)(num1*num2);
                        snum3=Long.toString(num3);
                        dato2=snum3.length();       
                pch=(dato2-dato)/2;
                if(dato%2!=0){snum4=snum3.substring(pch+1, (pch+1)+dato);
                }else{snum4=snum3.substring(pch, pch+dato);}
                     num4= Double.parseDouble(snum4)/(Math.pow(10, dato));
                     snum= Long.toString(num1);
                    fila[0]=Integer.toString(i);
                    fila[1]=snum2;
                    fila[2]=snum;
                    fila[3]=snum3;
                    fila[4]=snum4;
                    fila[5]=Double.toString(num4);
                    modelo.addRow(fila);
                    num1=Long.parseLong(snum4);
                    }
           }if (dato%2!=0) {
               for(i=0;i<Integer.parseInt(re);i++){
                 num3 = (long)(num1*num2);
                 snum3 = Long.toString(num3);
                 dato2 = snum3.length();
                 pch = (dato2-dato)/2;
                    if(dato%2==0){snum4 = snum3.substring(pch+1,+(pch+1)+dato);}
                    else {snum4=snum3.substring(pch, pch + dato);}
                    num4 = Double.parseDouble(snum4)/(Math.pow(10, dato));
                    snum= Long.toString(num1);
                    fila[0]=Integer.toString(i);
                    fila[1]=snum2;
                    fila[2]=snum;
                    fila[3]=snum3;
                    fila[4]=snum4;
                    fila[5]=Double.toString(num4);
                     modelo.addRow(fila);
                    num1=Long.parseLong(snum4);
              }         
           }
    }else{
        //De no haber seleccioando ningun Radio Button
 JOptionPane.showMessageDialog(null,"Debe indicar donde se colocara el 0","Aviso", JOptionPane.ERROR_MESSAGE);
        }      
    }//GEN-LAST:event_BGenerarMouseClicked
    
            
       
    private void Semillax0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Semillax0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Semillax0ActionPerformed

    private void B2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B2MouseClicked
      try {
                int b = T1.getRowCount();
                for (int n = b - 1; n >= 0;) {
                    modelo.removeRow(n);
                    n = n - 1;
                }
            } catch (Exception e) {
            }
       
        Constante.setText("");
        Semillax0.setText("");
        Repeticiones.setText("");
        CD.setSelected(false);
        CI.setSelected(false);
    }//GEN-LAST:event_B2MouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(NCMultiplicadorConstante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(NCMultiplicadorConstante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(NCMultiplicadorConstante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(NCMultiplicadorConstante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                NCMultiplicadorConstante dialog = new NCMultiplicadorConstante(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B2;
    private javax.swing.JButton BGenerar;
    private javax.swing.JRadioButton CD;
    private javax.swing.JRadioButton CI;
    private javax.swing.JTextField Constante;
    private javax.swing.JTextField Repeticiones;
    private javax.swing.JTextField Semillax0;
    private javax.swing.JTable T1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
